pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- bash: |
    wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.27.0
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: "Download golangci-lint"
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- bash: |
    make build
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: "make build"
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/presidio-anonymizer/cmd/presidio-anonymizer/'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(modulePath)'
- bash: |
    golangci-lint run ./...
  workingDirectory: '$(System.DefaultWorkingDirectory)'
