ARG REGISTRY=presidio.azurecr.io
ARG PRESIDIO_DEPS_LABEL=latest

FROM ${REGISTRY}/presidio-golang-deps:${PRESIDIO_DEPS_LABEL}


COPY go.mod $GOPATH/src/github.com/Microsoft/presidio/
WORKDIR $GOPATH/src/github.com/Microsoft/presidio
RUN go mod tidy

ADD . $GOPATH/src/github.com/Microsoft/presidio
RUN make go-test
