# This template performs required golang environment changes before running
# dep ensure. It is required for go <1.11, as noted in ADO golang docs:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/gso?view=azure-devops&tabs=go-older
steps:
- task: GoTool@0
  inputs:
    version: '1.14.6'
  displayName: "Setup Go Env - Go Tool"
- task: Bash@3
  displayName: 'Prepare directories'
  inputs:
    targetType: 'inline'
    script: |
      set -eux  # fail on error

      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b '$(GOBIN)' v1.27.0
      rm -rf '$(MODULEPATH)'
      mkdir -p '$(MODULEPATH)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(MODULEPATH)' --force
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
